# Generated by Django 4.1.7 on 2023-03-04 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_number', models.IntegerField()),
                ('booking_name', models.CharField(max_length=255)),
                ('invoice_no', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('contact_no', models.CharField(max_length=255)),
            ],
        ),
    ]
