# Generated by Django 4.1.7 on 2023-03-04 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingAuditTrail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.IntegerField()),
                ('field_name', models.CharField(max_length=100)),
                ('previous_data', models.CharField(max_length=100)),
                ('new_data', models.CharField(max_length=100)),
                ('done_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
